onlineCarShop/onlineCarShop/Models/Parts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineCarShop.Models
{
    public class Parts
    {
        public int Id { get; set; }

        [StringLength(100, MinimumLength = 2)]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "The field Name should only include letters and number.")]
        [DataType(DataType.Text)]
        [Required]
        public string Name { get; set; }

        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Price { get; set; }

        [StringLength(255, MinimumLength = 2)]
        [DataType(DataType.MultilineText)]
        [Required]
        public string Description { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        [DisplayName("Select Category")]
        public int PartsCategoriesId { get; set; }

        public virtual PartsCategories PartsCategory { get; set; }


        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}

onlineCarShop/onlineCarShop/ViewModels/SearchCarsViewModel.cs
using OnlineCarShop.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineCarShop.ViewModels
{
    public class SearchCarsViewModel
    {
        [Required]
        [DisplayName("Serach")]
        public string SearchText { get; set; }

        public IEnumerable<Cars> CarList { get; set; }

    }
}

onlineCarShop/onlineCarShop/Controllers/PartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineCarShop.Models;
using Microsoft.AspNetCore.Authorization;
using OnlineCarShop.ViewModels;
using OnlineCarShop.Data;
using OnlineCarShop.Repositories;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace OnlineCarShop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPartRepository _partRepo;
        private readonly IPartsCategoryRepository _categoryRepo;
        private readonly IHostingEnvironment env = null;
        IServiceProvider services=null;
        public PartsController(ApplicationDbContext context, IPartRepository carRepo
            , IPartsCategoryRepository categoryRepo
            , IHostingEnvironment ev,
            IServiceProvider _services)
        {
            _context = context;
            _partRepo = carRepo;
            _categoryRepo = categoryRepo;
            env = ev;
            services = _services;
        }
        [AllowAnonymous]
        public IActionResult AddToShoppingCart(int Partid) {
          
            String sessionId= HttpContext.Session.GetString("CartId");
            var oldItem = _context.ShoppingCartItems.FirstOrDefault(i => i.PartId == Partid && i.ShoppingCartId ==sessionId);
            ShoppingCartItem SCI = new ShoppingCartItem();
            SCI.Amount = 1;
            Parts  part= _context.Parts.Include(p=>p.PartsCategory).FirstOrDefault(p=>p.Id==Partid);
            if (part != null) {
                if (oldItem == null)
                {
                    SCI.Part = part;
                    SCI.ShoppingCartId = sessionId;
                    _context.Add(SCI);
                    _context.SaveChanges();
                }
                else {
                    oldItem.Amount += 1; 
                    _context.ShoppingCartItems.Update(oldItem);
                    _context.SaveChanges();
                }
            }
          

          
            return RedirectToAction("Index", "ShoppingCart");
        }
        [AllowAnonymous]
        public IActionResult RemoveToShoppingCart(int Partid)
        {

            String sessionId = HttpContext.Session.GetString("CartId");
            var oldItem = _context.ShoppingCartItems.FirstOrDefault(i => i.PartId == Partid && i.ShoppingCartId == sessionId);
            if (oldItem.Amount > 1)
            {
                oldItem.Amount -= 1;
                _context.ShoppingCartItems.Update(oldItem);
                _context.SaveChanges();

            }
            else {
                _context.ShoppingCartItems.Remove(oldItem);
                _context.SaveChanges();

            }


            return RedirectToAction("Index", "ShoppingCart");
        }
        // GET: 
        public async Task<IActionResult> Index()
        {
            return View(await _partRepo.GetAllIncludedAsync());
        }

        // GET: 
        [AllowAnonymous]
        public async Task<IActionResult> ListAll()
        {
            var model = new SearchPartsViewModel()
            {
                PartList = await _partRepo.GetAllIncludedAsync(),
                SearchText = null
            };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ListAll([Bind("SearchText")] SearchPartsViewModel model)
        {
            var cars = await _partRepo.GetAllIncludedAsync();
            if (model.SearchText == null || model.SearchText == string.Empty)
            {
                model.PartList = cars;
                return View(model);
            }

            var input = model.SearchText.Trim();
            if (input == string.Empty || input == null)
            {
                model.PartList = cars;
                return View(model);
            }
            var search = input.ToLower();

            if (string.IsNullOrEmpty(search))
            {
                model.PartList = cars;
            }
            else
            {
                var carList = _context.Parts.Include(x => x.PartsCategory).Include(x => x.Reviews).OrderBy(x => x.Name)
                     .Where(p =>
                     p.Name.ToLower().Contains(search)
                  || p.Price.ToString("c").ToLower().Contains(search)
                  || p.PartsCategory.Name.ToLower().Contains(search)).ToList();

                if (carList.Any())
                {
                    model.PartList = carList;
                }
                else
                {
                    model.PartList = new List<Parts>();
                }

            }
            return View(model);
        }

        // GET: 
        [AllowAnonymous]
        public async Task<IActionResult> ListCategory(string categoryName)
        {
            bool categoryExtist = _context.PartsCategories.Any(c => c.Name == categoryName);
            if (!categoryExtist)
            {
                return NotFound();
            }

            var category = await _context.PartsCategories.FirstOrDefaultAsync(c => c.Name == categoryName);

            if (category == null)
            {
                return NotFound();
            }

            bool anyCars = await _context.Parts.AnyAsync(x => x.PartsCategory == category);
            if (!anyCars)
            {
                return NotFound($"No Part were found in the category: {categoryName}");
            }

            var cars = _context.Parts.Where(x => x.PartsCategory == category)
                .Include(x => x.PartsCategory).Include(x => x.Reviews);

            ViewBag.CurrentCategory = category.Name;
            return View(cars);
        }

        // GET: /Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cars = await _partRepo.GetByIdIncludedAsync(id);

            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }

        // GET: /Details/5
        [AllowAnonymous]
        public async Task<IActionResult> DisplayDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cars = await _partRepo.GetByIdIncludedAsync(id);

         
            double score;
            if (_context.Reviews.Any(x => x.CarId == id))
            {
                var review = _context.Reviews.Where(x => x.CarId == id);
                score = review.Average(x => x.Grade);
                score = Math.Round(score, 2);
            }
            else
            {
                score = 0;
            }
            ViewBag.AverageReviewScore = score;

            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }

        // GET: 
        [AllowAnonymous]
        public async Task<IActionResult> SearchCars()
        {
            var model = new SearchPartsViewModel()
            {
                PartList = await _partRepo.GetAllIncludedAsync(),
                SearchText = null
            };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchCars([Bind("SearchText")] SearchPartsViewModel model)
        {
            var cars = await _partRepo.GetAllIncludedAsync();
            var search = model.SearchText.ToLower();

            if (string.IsNullOrEmpty(search))
            {
                model.PartList = cars;
            }
            else
            {
                var carList = await _context.Parts.Include(x => x.PartsCategory).Include(x => x.Reviews).OrderBy(x => x.Name)
                    .Where(p =>
                     p.Name.ToLower().Contains(search)
                  || p.Price.ToString("c").ToLower().Contains(search)
                  || p.PartsCategory.Name.ToLower().Contains(search)).ToListAsync();

                if (carList.Any())
                {
                    model.PartList = carList;
                }
                else
                {
                    model.PartList = new List<Parts>();
                }

            }
            return View(model);
        }

        // GET: /Create
        public IActionResult Create()
        {
            ViewData["CategoriesId"] = new SelectList(_categoryRepo.GetAll(), "Id", "Name");
            return View();
        }

        // POST: /Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,ImageUrl,PartsCategoriesId")] Parts parts)
        {
            if (ModelState.IsValid)
            {
                string webroorpath = env.WebRootPath;
                string DirPath = webroorpath + "/ImagesPart/";
                string imagefilename = Request.Form.Files["ImageUrl"].FileName;
                string fileext = Path.GetExtension(imagefilename);
                string customfilename = parts.Name + DateTime.Now.ToString("ddMMyyyyhhmmss") + fileext;
                string fullsavepath = @DirPath + customfilename;


                //Add new Image
                if (fileext != null && fileext != "")
                {
                    FileStream FS = new FileStream(fullsavepath, System.IO.FileMode.Create);

onlineCarShop/onlineCarShop/Views/Parts/Create.cshtml
@model Parts

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Cars</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">

                <label class="btn btn-primary btn-file">
                    <i class="glyphicon glyphicon-upload"></i>Browse image  <input type="file" id="ImageUrl" name="ImageUrl" style="display: none;">
                </label>
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
        </div>

       

        <div class="form-group">
            <label asp-for="PartsCategoriesId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="PartsCategoriesId" class ="form-control" asp-items="ViewBag.CategoriesId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

onlineCarShop/onlineCarShop/Views/Parts/Delete.cshtml
@model OnlineCarShop.Models.Parts

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Car?</h3>
<div>
    <h4>Cars</h4>
    <hr />
    <input type="hidden" asp-for="Id" />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.PartsCategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartsCategory.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

onlineCarShop/onlineCarShop/Views/Parts/Details.cshtml
@model Parts

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pizzas</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.PartsCategory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PartsCategory.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

onlineCarShop/onlineCarShop/Views/Parts/DisplayDetails.cshtml
@model Parts

@{
    var ModelName = "Part Details";
    ViewData["Title"] = ModelName;
}

<h2>@ModelName</h2>
<hr />

<p>
    <a asp-action="ListAll">Back to List</a>
</p>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl" height="800" width="800" class="img-responsive" >
    <div class="caption-full">
        <h2 class="pull-right">@Model.Price.ToString("c")</h2>
        <h2>
            <a href="">@Model.Name</a>
        </h2>
        <div>
        <h4>Category: <b> @Model.PartsCategory.Name </b></h4>
        <p>@Model.Description</p>
        <p>
      
        </p>
            
        </div>

        <br />
        <p class="button">
            <a class="btn btn-primary"asp-controller="Parts" asp-action="AddToShoppingCart"
                asp-route-partId="@Model.Id">Add Part</a>
        </p>
    </div>
</div>

onlineCarShop/onlineCarShop/Views/Parts/Edit.cshtml
@model OnlineCarShop.Models.Parts

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit"   enctype="multipart/form-data">
    
    <div class="form-horizontal" >
        <h4>Cars</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <input type="hidden" id="oldImageUrl" value="@Model.ImageUrl" name="oldImageUrl" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">

                <label class="btn btn-primary btn-file">
                    <i class="glyphicon glyphicon-upload"></i>Browse image  <input type="file" id="ImageUrl" name="ImageUrl" style="display: none;">
                </label>
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
        </div>
  
    
        <div class="form-group">
            <label asp-for="PartsCategoriesId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="PartsCategoriesId" class="form-control" asp-items="ViewBag.CategoriesId"></select>
                <span asp-validation-for="PartsCategoriesId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $("#IsMostDemandCar").val("true");
    </script>
}

onlineCarShop/onlineCarShop/Views/Parts/Index.cshtml
@model IEnumerable<Parts>

@{
    var pageName = "Cars";
    ViewData["Title"] = pageName;
}

<h2>@pageName</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
 
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>
              
            <th>
                @Html.DisplayNameFor(model => model.PartsCategory)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageUrl)
            </td>
         
            <td>
                @Html.DisplayFor(modelItem => item.PartsCategory.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

onlineCarShop/onlineCarShop/Views/Parts/ListAll.cshtml
@model SearchPartsViewModel

@{
    var pageName = "Parts Menu";
    ViewData["Title"] = pageName;
}

<h2>@pageName</h2>
<form asp-controller="Parts" asp-action="ListAll">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="SearchText" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SearchText" class="form-control" />
                <span asp-validation-for="SearchText" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-info" />
            </div>
        </div>
    </div>
</form>

@if (Model.SearchText != null)
{
    <h4>Results</h4>
}
else
{
    <h4>All Parts</h4>
}
<hr />

@foreach (var car in Model.PartList)
{
    @Html.Partial("PartSummary", car)
}
<br />

onlineCarShop/onlineCarShop/Views/Parts/ListCategory.cshtml
@model IEnumerable<Parts>

@{
    var pageName = ViewBag.CurrentCategory;
    ViewData["Title"] = pageName;
}

<h2>@pageName   Cars</h2>
<hr />

@foreach (var car in Model)
{
    @Html.Partial("PartSummary", car)
}
<br />

onlineCarShop/onlineCarShop/Views/Parts/SearchCars.cshtml
@model SearchCarsViewModel

@{
    var ModelName = "Search Cars";
    ViewData["Title"] = ModelName;
}

<h2>@ModelName</h2>
<form asp-controller="Cars" asp-action="SearchCars">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="SearchText" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SearchText" class="form-control" />
                <span asp-validation-for="SearchText" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-info" />
            </div>
        </div>
    </div>
</form>

<h4>Results</h4>
<hr />

@foreach (var car in Model.CarList)
{
    @Html.Partial("CarSummary", car)
}
<br />