onlineCarShop/onlineCarShop/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineCarShop.Models;
using Microsoft.AspNetCore.Authorization;
using OnlineCarShop.ViewModels;
using OnlineCarShop.Data;
using OnlineCarShop.Repositories;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace OnlineCarShop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICarRepository _carRepo;
        private readonly ICategoryRepository _categoryRepo;
        private readonly IHostingEnvironment env = null;
        public CarsController(ApplicationDbContext context, ICarRepository carRepo
            , ICategoryRepository categoryRepo
            ,IHostingEnvironment ev)
        {
            _context = context;
            _carRepo = carRepo;
            _categoryRepo = categoryRepo;
            env = ev;
        }

        // GET: 
        public async Task<IActionResult> Index()
        {
            return View(await _carRepo.GetAllIncludedAsync());
        }

        // GET: 
        [AllowAnonymous]
        public async Task<IActionResult> ListAll()
        {
            var model = new SearchCarsViewModel()
            {
                CarList = await _carRepo.GetAllIncludedAsync(),
                SearchText = null
            };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ListAll([Bind("SearchText")] SearchCarsViewModel model)
        {
            var cars = await _carRepo.GetAllIncludedAsync();
            if (model.SearchText == null || model.SearchText == string.Empty)
            {
                model.CarList = cars;
                return View(model);
            }

            var input = model.SearchText.Trim();
            if (input == string.Empty || input == null)
            {
                model.CarList = cars;
                return View(model);
            }
            var search = input.ToLower();

            if (string.IsNullOrEmpty(search))
            {
                model.CarList = cars;
            }
            else
            {
                var carList =  _context.Cars.Include(x => x.Category).Include(x => x.Reviews).OrderBy(x => x.Name)
                     .Where(p =>
                     p.Name.ToLower().Contains(search)
                  || p.Price.ToString("c").ToLower().Contains(search)
                  || p.Category.Name.ToLower().Contains(search)).ToList();

                if (carList.Any())
                {
                    model.CarList = carList;
                }
                else
                {
                    model.CarList = new List<Cars>();
                }

            }
            return View(model);
        }

        // GET: 
        [AllowAnonymous]
        public async Task<IActionResult> ListCategory(string categoryName)
        {
            bool categoryExtist = _context.Categories.Any(c => c.Name == categoryName);
            if (!categoryExtist)
            {
                return NotFound();
            }

            var category = await _context.Categories.FirstOrDefaultAsync(c => c.Name == categoryName);

            if (category == null)
            {
                return NotFound();
            }

            bool anyCars = await _context.Cars.AnyAsync(x => x.Category == category);
            if (!anyCars)
            {
                return NotFound($"No Car were found in the category: {categoryName}");
            }

            var cars = _context.Cars.Where(x => x.Category == category)
                .Include(x => x.Category).Include(x => x.Reviews);

            ViewBag.CurrentCategory = category.Name;
            return View(cars);
        }

        // GET: /Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cars = await _carRepo.GetByIdIncludedAsync(id);

            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }

        // GET: /Details/5
        [AllowAnonymous]
        public async Task<IActionResult> DisplayDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cars = await _carRepo.GetByIdIncludedAsync(id);

            //var listOfParts = await _context.CarParts.Where(x => x.CarId == id).Select(x => x.Part.Name).ToListAsync();
            //ViewBag.CarParts = listOfParts;

            //var listOfReviews = await _context.Reviews.Where(x => x.CarId == id).Select(x => x).ToListAsync();
            //ViewBag.Reviews = listOfReviews;
            double score;
            if (_context.Reviews.Any(x => x.CarId == id))
            {
                var review = _context.Reviews.Where(x => x.CarId == id);
                score = review.Average(x => x.Grade);
                score = Math.Round(score, 2);
            }
            else
            {
                score = 0;
            }
            ViewBag.AverageReviewScore = score;

            if (cars == null)
            {
                return NotFound();
            }

            return View(cars);
        }

        // GET: 
        [AllowAnonymous]
        public async Task<IActionResult> SearchCars()
        {
            var model = new SearchCarsViewModel()
            {
                CarList = await _carRepo.GetAllIncludedAsync(),
                SearchText = null
            };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchCars([Bind("SearchText")] SearchCarsViewModel model)
        {
            var cars = await _carRepo.GetAllIncludedAsync();
            var search = model.SearchText.ToLower();

            if (string.IsNullOrEmpty(search))
            {
                model.CarList = cars;
            }
            else
            {
                var carList = await _context.Cars.Include(x => x.Category).Include(x => x.Reviews).OrderBy(x => x.Name)
                    .Where(p =>
                     p.Name.ToLower().Contains(search)
                  || p.Price.ToString("c").ToLower().Contains(search)
                  || p.Category.Name.ToLower().Contains(search)).ToListAsync();

                if (carList.Any())
                {
                    model.CarList = carList;
                }
                else
                {
                    model.CarList = new List<Cars>();
                }

            }
            return View(model);
        }

        // GET: /Create
        public IActionResult Create()
        {
            ViewData["CategoriesId"] = new SelectList(_categoryRepo.GetAll(), "Id", "Name");
            return View();
        }

        // POST: /Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Description,ImageUrl,IsMostDemandCar,CategoriesId")] Cars cars)
        {
            if (ModelState.IsValid)
            {
                string webroorpath = env.WebRootPath;
                string DirPath = webroorpath + "/ImagesCar/";
                string imagefilename = Request.Form.Files["ImageUrl"].FileName;
                string fileext = Path.GetExtension(imagefilename);
                string customfilename = cars.Name + DateTime.Now.ToString("ddMMyyyyhhmmss") + fileext;
                string fullsavepath = @DirPath + customfilename;

               
                //Add new Image
                if (fileext != null && fileext != "")
                {
                    FileStream FS = new FileStream(fullsavepath, System.IO.FileMode.Create);
                    Request.Form.Files["ImageUrl"].CopyTo(FS);
                    FS.Close();
                    cars.ImageUrl = @"/ImagesCar/" + customfilename;
                 
                }
                else
                {
                    cars.ImageUrl = @"/ImagesCar/" + @"defaultImage.png";

                }
             
                _carRepo.Add(cars);
                await _carRepo.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CategoriesId"] = new SelectList(_categoryRepo.GetAll(), "Id", "Name", cars.CategoriesId);
            return View(cars);
        }

        // GET: /Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cars = await _carRepo.GetByIdAsync(id);

            if (cars == null)
            {
                return NotFound();
            }
            ViewData["CategoriesId"] = new SelectList(_categoryRepo.GetAll(), "Id", "Name", cars.CategoriesId);
            return View(cars);
        }

        // POST: /Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, String oldImageUrl, [Bind("Id,Name,Price,Description,ImageUrl,IsMostDemandCar,CategoriesId")] Cars car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

onlineCarShop/onlineCarShop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineCarShop.Repositories;
using OnlineCarShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using OnlineCarShop.Data;
using System.Net.Mail;
using Microsoft.AspNetCore.Hosting;

namespace OnlineCarShop.Controllers
{
    [Authorize(Roles = "Admin")]
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment env;

        public OrdersController(IOrderRepository orderRepository, 
            ShoppingCart shoppingCart, ApplicationDbContext context, UserManager<ApplicationUser> userManager
            , IHostingEnvironment _env)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
            _context = context;
            _userManager = userManager;
            env = _env;
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            order.UserId = userId;

            var items = await _shoppingCart.GetShoppingCartItemsAsync();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some Items first");
            }

            if (ModelState.IsValid)
            {
                await _orderRepository.CreateOrderAsync(order);
                await _shoppingCart.ClearCartAsync();
                TempData["orderid"] = order.OrderId;
                TempData["ordertotal"] = order.OrderTotal;
                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        [Authorize]
        public IActionResult CheckoutComplete()
        {
            try
            {
                int orderid = Convert.ToInt32(TempData["orderid"]);
                int ordertotal = Convert.ToInt32(TempData["ordertotal"]);
                var userId = _userManager.GetUserId(HttpContext.User);
                ApplicationUser user=_userManager.Users.FirstOrDefault(u=>u.Id==userId);
             
                string rootPath = env.WebRootPath;
               
                MailMessage EmailObject = new MailMessage();
                EmailObject.From = new MailAddress("onlinecarshop01@gmail.com", " Online Car Shop");
                EmailObject.To.Add(new MailAddress(user.Email));
                EmailObject.Subject = "Order Confirmation";
                EmailObject.Body = "Thanks for your order, We'll deliver your Items soon!<br/>"+ "Your Order Id is:"+ orderid + "<br/>Total Amount is: $"+ordertotal;
                EmailObject.IsBodyHtml = true;
                SmtpClient SC = new SmtpClient("smtp.gmail.com", 587);
                SC.Credentials = new System.Net.NetworkCredential("onlinecarshop01@gmail.com", "Password@123");
                SC.EnableSsl = true;
                SC.Send(EmailObject);

                ViewBag.message = "Check your inbox,Email send at : "+user.Email;

            }
            catch (Exception)
            {
                ViewBag.message = "Email Not sent ,Please Contact with Us on 0300-1234567";
            }
          
            ViewBag.CheckoutCompleteMessage = $"Thanks for your order, We'll deliver your Items soon!";
            return View();
        }

        // GET: Reviews
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            bool isAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            if (isAdmin)
            {
                var allOrders = await _context.Orders.Include(o => o.OrderLines).Include(o => o.User).ToListAsync();
                return View(allOrders);
            }
            else
            {
                var orders = await _context.Orders.Include(o => o.OrderLines).Include(o => o.User)
                    .Where(r => r.User == user).ToListAsync();
                return View(orders);
            }
        }

        // GET: Orders/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var orders = await _context.Orders.Include(o => o.OrderLines).Include(o => o.User)
                .SingleOrDefaultAsync(m => m.OrderId == id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var userRoles = await _userManager.GetRolesAsync(user);
            bool isAdmin = userRoles.Any(r => r == "Admin");

            if (orders == null)
            {
                return NotFound();
            }

            if (isAdmin == false)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                if (orders.UserId != userId)
                {
                    return BadRequest("You do not have permissions to view this order.");
                }
            }

            var orderDetailsList = _context.OrderDetails.Include(o => o.Car).Include(o => o.Order)
                .Where(x => x.OrderId == orders.OrderId);

            ViewBag.OrderDetailsList = orderDetailsList;

            return View(orders);
        }

        [Authorize(Roles = "Admin")]
        // GET: Orders/Edit/5
        public IActionResult Edit(int id)
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        // POST: Orders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.Include(o => o.User)
                .SingleOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: OrdersTest/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.SingleOrDefaultAsync(m => m.OrderId == id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

onlineCarShop/onlineCarShop/Views/Shared/CarSummary.cshtml
@model Cars

@{
    ViewData["Title"] = "CarSummary";
}
<style>
    .thumbnail img {
        height: 200px;
        width: 250px;
    }

</style>
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img class="img-thumbnail img-responsive"
             href=""
             src="@Html.DisplayFor(model=>model.ImageUrl)"
             alt="Car Image Not Found"/>
      
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Cars" asp-action="DisplayDetails" asp-route-id="@Model.Id">@Model.Name</a>
            </h3>
            <h5><b>Category: @Model.Category.Name</b></h5>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-carId="@Model.Id">Add Car</a>
            </p>
        </div>
    </div>
</div>

onlineCarShop/onlineCarShop/Views/Shared/PartSummary.cshtml
@model Parts

@{
    ViewData["Title"] = "Part Summary";
}
<style>
    .thumbnail img {
        height: 200px;
        width: 250px;
    }

</style>
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img class="img-thumbnail img-responsive"
             href=""
             src="@Html.DisplayFor(model=>model.ImageUrl)"
             alt="Car Image Not Found"/>
      
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Parts" asp-action="DisplayDetails" asp-route-id="@Model.Id">@Model.Name</a>
            </h3>
            <h5><b>Category: @Model.PartsCategory.Name</b></h5>
            <p>@Model.Description</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="Parts" asp-action="AddToShoppingCart"
                   asp-route-partId="@Model.Id">Add Part</a>
            </p>
        </div>
    </div>
</div>

onlineCarShop/onlineCarShop/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

<!DOCTYPE html>
<html>
<head>
   
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Shop</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
  
   
   
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="color: white;" asp-controller="Home" asp-action="Index" class="navbar-brand">Car Shop</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Cars" asp-action="ListAll">Cars</a></li>
                    <li><a asp-controller="Parts" asp-action="ListAll">Parts</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    @await Component.InvokeAsync("PartsCategoryMenu")
                    @if (User.Identity!=null)
                    {
                        <li><a asp-controller="Reviews" asp-action="Index">Reviews</a></li>
                        <li><a asp-controller="Orders" asp-action="Index">Orders</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Reviews" asp-action="ListAll">Reviews</a></li>
                    }
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    @if (User.IsInRole("Admin"))
    {
       
        <div class="row">
      
            <div id="adminMenue" class="col-md-3 col-md-push-1 ">
               
                    <h3><a asp-controller="Cars" asp-action="Index">Cars</a></h3>
                    <h3><a asp-controller="Categories" asp-action="Index">Car Categories</a></h3>
                    <h3><a asp-controller="Parts" asp-action="Index">Parts</a></h3>
                    <h3><a asp-controller="PartsCategories" asp-action="Index">Parts Catagories</a></h3>
                    <h3><a asp-controller="Reviews" asp-action="AdminIndex">Reviews</a></h3>
                    <h3><a asp-controller="Orders" asp-action="Index">Orders</a></h3>
                    @*<h3><a asp-controller="Admin" asp-action="SeedDatabaseAsync">Seed Database</a></h3>
                    <h3><a asp-controller="Admin" asp-action="ClearDatabaseAsync">Clear Database</a></h3>*@
                
            </div>
            
            <div class="col-md-7 ">

              

                    @RenderBody()

                <div class="clearfix"></div>
                    <hr />
                    <footer>
                        <p>
                            <div><a asp-controller="Home" asp-action="About"><b>About</b></a></div>
                            <div><a asp-controller="Home" asp-action="Contact"><b>Contact</b></a></div>
                            <div>&copy; Lahore @DateTime.Now.Year - Car Shop</div>
                        </p>
                    </footer>
                </div>
            </div>
        
    }
    else
    {
        <div class="container body-content">

            @RenderBody()

            <div class="clearfix"></div>
            <hr />
            <footer>
                <p>
                    <div><a asp-controller="Home" asp-action="About"><b>About</b></a></div>
                    <div><a asp-controller="Home" asp-action="Contact"><b>Contact</b></a></div>
                    <div>&copy; Lahore @DateTime.Now.Year - Car Shop</div>
                </p>
            </footer>
        </div>
    }

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

@*<script>
     $(function () {

         $('#adminMenue').load("/Admin/Index");


     });
</script>*@