onlineCarShop/onlineCarShop/Models/Cars.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;



namespace OnlineCarShop.Models
{
    public class Cars 
    {
        public int Id { get; set; }

        [StringLength(100, MinimumLength = 2)]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "The field Name should only include letters and number.")]
        [DataType(DataType.Text)]
        [Required]
        public string Name { get; set; }

        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Price { get; set; }

        [StringLength(255, MinimumLength = 2)]
        [DataType(DataType.MultilineText)]
        [Required]
        public string Description { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        public bool IsMostDemandCar { get; set; }

        [DisplayName("Select Category")]
        public int CategoriesId { get; set; }

        public virtual Categories Category { get; set; }

  
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}

onlineCarShop/onlineCarShop/ViewModels/SearchCarsViewModel.cs
using OnlineCarShop.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineCarShop.ViewModels
{
    public class SearchCarsViewModel
    {
        [Required]
        [DisplayName("Serach")]
        public string SearchText { get; set; }

        public IEnumerable<Cars> CarList { get; set; }

    }
}

onlineCarShop/onlineCarShop/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineCarShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using OnlineCarShop.Data;

namespace OnlineCarShop.Controllers
{
    [Authorize]
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReviewsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AdminIndex()
        {
            var reviews = await _context.Reviews.Include(r => r.Car).Include(r => r.User).ToListAsync();
            return View(reviews);
        }

        // GET: Reviews
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            //bool isAdmin = await _userManager.IsInRoleAsync(user, "Admin");

       
                var reviews = _context.Reviews.Include(r => r.Car).Include(r => r.User)
                    .Where(r => r.User == user).ToList();
                return View(reviews);
            
        }

        // GET: Reviews
        [AllowAnonymous]
        public async Task<IActionResult> ListAll()
        {
            var reviews = await _context.Reviews.Include(r => r.Car).Include(r => r.User).ToListAsync();
            return View(reviews);
        }

        // GET: Reviews
        [AllowAnonymous]
        public async Task<IActionResult> CarReviews(int? carId)
        {
            if (carId == null)
            {
                return NotFound();
            }
            var car = _context.Cars.FirstOrDefault(x => x.Id == carId);
            if (car == null)
            {
                return NotFound();
            }
            var reviews = await _context.Reviews.Include(r => r.Car).Include(r => r.User).Where(x => x.Car.Id == car.Id).ToListAsync();
            if (reviews == null)
            {
                return NotFound();
            }
            ViewBag.CarName = car.Name;
            ViewBag.CarId = car.Id;

            return View(reviews);
        }

        // GET: Reviews/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews
                .Include(r => r.Car)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (reviews == null)
            {
                return NotFound();
            }

            return View(reviews);
        }

        // GET: Reviews/Create
        public IActionResult CreateWithCar(int? carId)
        {
            var review = new Reviews();

            if (carId == null)
            {
                return NotFound();
            }

            var car = _context.Cars.FirstOrDefault(p => p.Id == carId);
            
            if (car == null)
            {
                return NotFound();
            }

            review.Car = car;
            review.CarId = car.Id;
            ViewData["CarId"] = new SelectList(_context.Cars.Where(p => p.Id == carId), "Id", "Name");
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value");

            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWithCar(int carId, Reviews reviews)
        {
            carId = reviews.CarId;
            if (carId != reviews.CarId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                reviews.UserId = userId;
                reviews.Date = DateTime.Now;

                _context.Add(reviews);
                await _context.SaveChangesAsync();
                return Redirect($"CarReviews?carId={carId}");
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["CarId"] = new SelectList(_context.Cars.Where(p => p.Id == carId), "Id", "Name", reviews.CarId);
            return View(reviews);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value");
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "Name");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CarId,Title,Description,Grade,CarId")] Reviews reviews)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            reviews.UserId = userId;
            if (ModelState.IsValid)
            {
              

                reviews.Date = DateTime.Now;
                await _context.Reviews.AddAsync(reviews);
                //_context.Add(reviews);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "Name", reviews.CarId);
            
            return View(reviews);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews.SingleOrDefaultAsync(m => m.Id == id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var userRoles = await _userManager.GetRolesAsync(user);
            bool isAdmin = userRoles.Any(r => r == "Admin");

            if (reviews == null)
            {
                return NotFound();
            }

            if (isAdmin == false)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                if (reviews.UserId != userId)
                {
                    return BadRequest("You do not have permissions to edit this review.");
                }
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "Name", reviews.CarId);
            return View(reviews);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CarId,Title,Description,Grade,Date,CarId")] Reviews reviews)
        {
            if (id != reviews.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                try
                {
                   
                        reviews.Date = DateTime.Now;
                    
                    reviews.UserId = userId;

                    _context.Update(reviews);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewsExists(reviews.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["carId"] = new SelectList(_context.Cars, "Id", "Name", reviews.CarId);
            return View(reviews);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews
                .Include(r => r.Car)
                .SingleOrDefaultAsync(m => m.Id == id);

onlineCarShop/onlineCarShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineCarShop.Repositories;
using OnlineCarShop.Models;
using OnlineCarShop.ViewModels;
using OnlineCarShop.Data;

namespace OnlineCarShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ICarRepository _carRepository;
        private readonly ApplicationDbContext _context;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(ICarRepository carRepository,
            ShoppingCart shoppingCart, ApplicationDbContext context)
        {
            _carRepository = carRepository;
            _shoppingCart = shoppingCart;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var items = await _shoppingCart.GetShoppingCartItemsAsync();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public async Task<IActionResult> AddToShoppingCart(int carId)
        {
            var selectedCar = await _carRepository.GetByIdAsync(carId);

            if (selectedCar != null)
            {
                await _shoppingCart.AddToCartAsync(selectedCar, 1);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveFromShoppingCart(int carId)
        {
            var selectedCar = await _carRepository.GetByIdAsync(carId);

            if (selectedCar != null)
            {
                await _shoppingCart.RemoveFromCartAsync(selectedCar);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ClearCart()
        {
            await _shoppingCart.ClearCartAsync();

            return RedirectToAction("Index");
        }

    }
}

onlineCarShop/onlineCarShop/Views/Cars/Create.cshtml
@model Cars

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Cars</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">

                <label class="btn btn-primary btn-file">
                    <i class="glyphicon glyphicon-upload"></i>Browse image  <input type="file" id="ImageUrl" name="ImageUrl" style="display: none;">
                </label>
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
        </div>

        @Html.CheckBox("IsMostDemandCar", false)

        <div class="form-group">
            <label asp-for="CategoriesId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CategoriesId" class ="form-control" asp-items="ViewBag.CategoriesId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

onlineCarShop/onlineCarShop/Views/Cars/Delete.cshtml
@model OnlineCarShop.Models.Cars

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Car?</h3>
<div>
    <h4>Cars</h4>
    <hr />
    <input type="hidden" asp-for="Id" />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsMostDemandCar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsMostDemandCar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

onlineCarShop/onlineCarShop/Views/Cars/Details.cshtml
@model Cars

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pizzas</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsMostDemandCar)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsMostDemandCar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

onlineCarShop/onlineCarShop/Views/Cars/DisplayDetails.cshtml
@model Cars

@{
    var ModelName = "Car Details";
    ViewData["Title"] = ModelName;
}

<h2>@ModelName</h2>
<hr />

<p>
    <a asp-action="ListAll">Back to List</a>
</p>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl" height="800" width="800" class="img-responsive" >
    <div class="caption-full">
        <h2 class="pull-right">@Model.Price.ToString("c")</h2>
        <h2>
            <a href="">@Model.Name</a>
        </h2>
        <div>
        <h4>Category: <b> @Model.Category.Name </b></h4>
        <p>@Model.Description</p>
        <p>
      
        </p>
            
                <p>
                    @if (ViewBag.AverageReviewScore > 0)
                    {
                        <h4>Average Review Score: <b> @ViewBag.AverageReviewScore </b></h4>
                    }
                    else
                    {
                        <h4>No Reviews was found. </h4>
                    }
                    @if (ViewBag.AverageReviewScore <= 0 || ViewBag.AverageReviewScore > 5)
                    {
                        <img class="img-responsive review-stars" src="~/images/0stars.png" alt="No Reviews was found." />
                    }
                    else if (ViewBag.AverageReviewScore > 4.5)
                    {
                        <img class="img-responsive review-stars" src="~/images/5stars.png" alt="5 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 4.0)
                    {
                        <img class="img-responsive review-stars" src="~/images/4.5stars.png" alt="4.5 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 3.5)
                    {
                        <img class="img-responsive review-stars" src="~/images/4stars.png" alt="4 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 3.0)
                    {
                        <img class="img-responsive review-stars" src="~/images/3.5stars.png" alt="3.5 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 2.5)
                    {
                        <img class="img-responsive review-stars" src="~/images/3stars.png" alt="3 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 2.0)
                    {
                        <img class="img-responsive review-stars" src="~/images/2.5stars.png" alt="2.5 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 1.5)
                    {
                        <img class="img-responsive review-stars" src="~/images/2stars.png" alt="2 stars picture." />
                    }
                    else if (ViewBag.AverageReviewScore > 1.0)
                    {
                        <img class="img-responsive review-stars" src="~/images/1.5stars.png" alt="1.5 stars picture." />
                    }
                    else
                    {
                        <img class="img-responsive  review-stars" src="~/images/1star.png" alt="1 star picture." />
                    }
                </p>
            
       
        <p>
            <h4>
                <a asp-controller="Reviews" asp-action="CarReviews" asp-route-carId="@Model.Id">Reviews</a>
            </h4>
        </p>
        </div>

        <br />
        <p class="button">
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                asp-route-carId="@Model.Id">Add Car</a>
        </p>
    </div>
</div>

onlineCarShop/onlineCarShop/Views/Cars/Edit.cshtml
@model OnlineCarShop.Models.Cars

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit"   enctype="multipart/form-data">
    
    <div class="form-horizontal" >
        <h4>Cars</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <input type="hidden" id="oldImageUrl" value="@Model.ImageUrl" name="oldImageUrl" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">

                <label class="btn btn-primary btn-file">
                    <i class="glyphicon glyphicon-upload"></i>Browse image  <input type="file" id="ImageUrl" name="ImageUrl" style="display: none;">
                </label>
                <span asp-validation-for="ImageUrl" class="text-danger" />
            </div>
        </div>
  
    
        <div class="form-group">
            <label asp-for="CategoriesId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="CategoriesId" class="form-control" asp-items="ViewBag.CategoriesId"></select>
                <span asp-validation-for="CategoriesId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $("#IsMostDemandCar").val("true");
    </script>
}

onlineCarShop/onlineCarShop/Views/Cars/Index.cshtml
@model IEnumerable<Cars>

@{
    var pageName = "Cars";
    ViewData["Title"] = pageName;
}

<h2>@pageName</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
 
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsMostDemandCar)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsMostDemandCar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

onlineCarShop/onlineCarShop/Views/Cars/ListAll.cshtml
@model SearchCarsViewModel

@{
    var pageName = "Cars Menu";
    ViewData["Title"] = pageName;
}

<h2>@pageName</h2>
<form asp-controller="Cars" asp-action="ListAll">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="SearchText" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SearchText" class="form-control" />
                <span asp-validation-for="SearchText" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-info" />
            </div>
        </div>
    </div>
</form>

@if (Model.SearchText != null)
{
    <h4>Results</h4>
}
else
{
    <h4>All Cars</h4>
}
<hr />

@foreach (var car in Model.CarList)
{
    @Html.Partial("CarSummary", car)
}
<br />

onlineCarShop/onlineCarShop/Views/Cars/ListCategory.cshtml
@model IEnumerable<Cars>

@{
    var pageName = ViewBag.CurrentCategory;
    ViewData["Title"] = pageName;
}

<h2>@pageName   Cars</h2>
<hr />

@foreach (var car in Model)
{
    @Html.Partial("CarSummary", car)
}
<br />

onlineCarShop/onlineCarShop/Views/Cars/SearchCars.cshtml
@model SearchCarsViewModel

@{
    var ModelName = "Search Cars";
    ViewData["Title"] = ModelName;
}

<h2>@ModelName</h2>
<form asp-controller="Cars" asp-action="SearchCars">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="SearchText" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SearchText" class="form-control" />
                <span asp-validation-for="SearchText" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-info" />
            </div>
        </div>
    </div>
</form>

<h4>Results</h4>
<hr />

@foreach (var car in Model.CarList)
{
    @Html.Partial("CarSummary", car)
}
<br />